### ISSUE TITLE
.tr domain UTF-8 charachter error

### ISSUE THREAD

**Issue by berkaybakacak** [richardpenman/whois#31] opened 2020-01-10 17:09 UTC
I'm trying to get a .tr domain whois data, api returns it, but Turkish characters do not appear. Where there are Turkish characters, the question mark appears in the diamond (�).

For example, I am trying to get whois data for "mimotto.com.tr". Result:

{'domain_name': 'mimotto.com.tr', 'creation_date': datetime.datetime(2017, 12, 27, 0, 0), 'expiration_date': datetime.datetime(2020, 12, 26, 0, 0), 'name_servers': 'ns1.interkeyservertr.com\nns2.interkeyservertr.com', 'registrant': 'TAL�H TASARIM DEKORASYON VE T�C.LTD.�T�.\n   Ye�iloba Mahallesi 46209 Sokak No:1E/1\n   Fuat Ya�murca Sanayi Sitesi / Seyhan\n   Adana,\n     T�rkiye\n   info@interkey.com.tr\n   + 90-322-5030642-\n   +', 'admin': None, 'admin_organization': None, 'admin_address': None, 'admin_phone': None, 'admin_fax': None, 'tech': None, 'tech_organization': None, 'tech_address': None, 'tech_phone': None, 'tech_fax': None, 'billing': None, 'billing_organization': None, 'billing_address': None, 'billing_phone': None, 'billing_fax': None}

**Comment by richardpenman** [comment] 2020-07-28 16:31
I tried this domain and get following:

    "registrant_name": "TAL\ufffdH TASARIM DEKORASYON VE T\ufffdC.LTD.\ufffdT\ufffd.\n   Ye\ufffdiloba Mahallesi 46209 Sokak No:1E/1\n   Fuat Ya\ufffdmurca Sanayi Sitesi / Seyhan\n   Adana,\n     T\ufffdrkiye\n   info@interkey.com.tr\n   + 90-322-5030642-\n   +"

those diamonds are a unicode character that needs to be decoded

**Comment by eyupakpinar** [comment] 2020-10-26 13:07
\ufffd is a replacement character . Is it possible to decode a replacement character?

**Comment by richardpenman** [comment] 2020-10-26 23:59
patch welcome

**Comment by eyupakpinar** [comment] 2020-10-27 05:53
I will check this issue.

**Comment by BaYStudyo** [comment] 2020-10-27 13:39
The error still exists

**Comment by BaYStudyo** [comment] 2020-11-08 07:19
The character \ufffd replaces all Turkish characters. I guess we will not be able to decode them. Maybe the problem is caused by the server from which the whois information is taken? Maybe that server doesn't support Turkish characters? What are your ideas? Will we be able to solve the problem?

**Comment by eyupakpinar** [comment] 2020-11-08 07:30
I used subprocess library for whois information in my project and it is worked. I'm too busy to review the code anytime soon and make any fixes but I have some ideas. In my opinion, there are encoding and decoding operations in this project. These operations break the structure of the string. The reason I think so is because when I get the whois output manually, I get the correct data.

**Comment by BaYStudyo** [comment] 2020-11-08 21:45
> I used subprocess library for whois information in my project and it is worked. I'm too busy to review the code anytime soon and make any fixes but I have some ideas. In my opinion, there are encoding and decoding operations in this project. These operations break the structure of the string. The reason I think so is because when I get the whois output manually, I get the correct data.

If the server/site where you manually get the data is the same as where this module automatically gets, your opinion is correct.
What would you say @richardpenman ?

**Comment by richardpenman** [comment] 2021-08-03 17:45
I would welcome a pull request that fixes this issue

**Comment by berkaybakacak** [comment] 2022-08-12 18:39
> Is there any progress on this?

unfortunatley, no...

**Comment by richardpenman** [comment] 2024-05-17 02:20
Closing as no one is motivated to create a PR for this issue

**Closed by richardpenman** 2024-05-17 02:20 UTC
